### ISSUE TITLE
Inconsistent aws_route behavior when using NAT gateways

### ISSUE THREAD

**Issue by smihajlovic-frame** [terraform-aws-modules/terraform-aws-vpc#102]
## Expected Behavior

VPC is created with 0.0.0.0/0 routes set to route to NAT gateways.

## Actual Behavior

AWS routes are created, but Terraform cannot find the created resources. Retrying would lead to the same error.

Output example when one route is created successfully and other fails:

> module.company-vpc.aws_route.private_nat_gateway[0]: Creation complete after 0s (ID: r-rtb-3ef046421080289494)
> module.company-vpc.aws_route.private_nat_gateway.1: Still creating... (10s elapsed)

Output example 1:

> Error: Error applying plan:
> 
> 2 error(s) occurred:
> 
> * module.company-vpc.aws_route.private_nat_gateway[1]: 1 error(s) occurred:
> 
> * aws_route.private_nat_gateway.1: Error finding route after creating it: Unable to find matching route for Route Table (rtb-571db42b) and destination CIDR block (0.0.0.0/0).
> * module.company-vpc.aws_route.private_nat_gateway[0]: 1 error(s) occurred:
> 
> * aws_route.private_nat_gateway.0: Error finding route after creating it: Unable to find matching route for Route Table (rtb-8302abff) and destination CIDR block (0.0.0.0/0).
> 

Output example 2:

> Error: Error applying plan:
> 2 error(s) occurred:
> * module.company-vpc.aws_route.private_nat_gateway[1]: 1 error(s) occurred:
> 
> * aws_route.private_nat_gateway.1: Error creating route: RouteAlreadyExists: The route identified by 0.0.0.0/0 already exists.
>        status code: 400, request id: cfbc621a-0b44-4e99-ae6e-bca550e6b922
> * module.company-vpc.aws_route.private_nat_gateway[0]: 1 error(s) occurred:
> 
> * aws_route.private_nat_gateway.0: Error creating route: RouteAlreadyExists: The route identified by 0.0.0.0/0 already exists.
>        status code: 400, request id: 932ad58d-0afb-44ef-9d43-589ddac154bf

Output example 3:

> Error: Error applying plan:
> 
> 2 error(s) occurred:
> 
> * module.company-vpc.aws_route.private_nat_gateway[0]: 1 error(s) occurred:
> 
> * aws_route.private_nat_gateway.0: Error creating route: RouteAlreadyExists: The route identified by 0.0.0.0/0 already exists.
>         status code: 400, request id: 27ef394a-7259-4225-ad41-73ebcd234f3b
> * module.company-vpc.aws_route.private_nat_gateway[1]: 1 error(s) occurred:
> 
> * aws_route.private_nat_gateway.1: Error creating route: RouteAlreadyExists: The route identified by 0.0.0.0/0 already exists.
>         status code: 400, request id: 23ace76b-06f9-4f2f-bb0f-bb093bd3d0c5
> 

## Steps to Reproduce the Problem

  1. Use VPC with private subnets and NAT gateway
  2. Run Terraform

## Specifications

  - Module Version: 1.26.0
  - Terraform Version: 0.11.3
  - AWS Provider Versions: ~> 1.8 & ~> 1.11

**Comment by antonbabenko** [comment]
Show the Terraform configuration you are using to be able to help you.

**Comment by smihajlovic-frame** [comment]
Here is the code for network provisioning:

```
provider "aws" {
  version     = "~> 1.8"
  max_retries = 5
  region      = "${var.region}"

  assume_role {
    role_arn    = "${var.backplane_aws_sts_assume_role ? format("%s%s%s", "arn:aws:iam::", var.backplane_aws_account_id, ":role/Terraform") : "" }"
    external_id = "${var.backplane_aws_sts_assume_role ? var.backplane_aws_sts_assume_role_external_id : "" }"
  }
}

module "company-vpc" {
  source  = "terraform-aws-modules/vpc/aws"
  version = "1.26.0"

  name = "company - ${var.company_sitename}"
  cidr = "${var.company_vpc_cidr_block}"

  azs              = "${var.company_vpc_subnet_azs}"
  private_subnets  = "${var.company_vpc_private_subnet_cidr_blocks}"
  public_subnets   = "${var.company_vpc_public_subnet_cidr_blocks}"
  database_subnets = "${var.company_vpc_database_subnet_cidr_blocks}"

  enable_nat_gateway               = true
  enable_dhcp_options              = true
  dhcp_options_domain_name         = "ec2.internal"
  dhcp_options_domain_name_servers = ["AmazonProvidedDNS"]

  create_database_subnet_group = false
  create_vpc                   = "${var.vpc_create}"
}

resource "aws_vpc_peering_connection" "installer_backplane_peering" {
  peer_owner_id = "${var.installer_aws_account_id}"
  peer_vpc_id   = "${var.installer_vpc_id}"
  vpc_id        = "${module.company-vpc.vpc_id}"

  tags {
    Name = "VPC Peering between installer and company backplane"
  }
}

############# PEERING ACCEPTER ########################

provider "aws" {
  alias  = "installer"
  region = "us-east-1"
}

resource "aws_vpc_peering_connection_accepter" "peer" {
  provider                  = "aws.installer"
  vpc_peering_connection_id = "${aws_vpc_peering_connection.installer_backplane_peering.id}"
  auto_accept               = true
}

############# ROUTING FROM INSTALLER INSTANCE TO company PLATFORM ###############

data "aws_route_table" "installer_subnet_rt" {
  provider  = "aws.installer"
  subnet_id = "${var.installer_subnet_id}"
}

resource "aws_route" "installer_route" {
  provider                  = "aws.installer"
  route_table_id            = "${data.aws_route_table.installer_subnet_rt.id}"
  destination_cidr_block    = "${var.company_vpc_cidr_block}"
  vpc_peering_connection_id = "${aws_vpc_peering_connection.installer_backplane_peering.id}"
}

############# ROUTING FROM company PLATFORM TO INSTALLER INSTANCE ###############

data "aws_subnet" "installer_subnet" {
  provider = "aws.installer"
  id       = "${var.installer_subnet_id}"
}

resource "aws_route" "company_private_route_1" {
  route_table_id            = "${module.company-vpc.private_route_table_ids[0]}"
  destination_cidr_block    = "${data.aws_subnet.installer_subnet.cidr_block}"
  vpc_peering_connection_id = "${aws_vpc_peering_connection.installer_backplane_peering.id}"
  depends_on                = ["module.company-vpc", "aws_vpc_peering_connection.installer_backplane_peering", "aws_vpc_peering_connection_accepter.peer"]
}

resource "aws_route" "company_private_route_2" {
  route_table_id            = "${module.company-vpc.private_route_table_ids[1]}"
  destination_cidr_block    = "${data.aws_subnet.installer_subnet.cidr_block}"
  vpc_peering_connection_id = "${aws_vpc_peering_connection.installer_backplane_peering.id}"
  depends_on                = ["module.company-vpc", "aws_vpc_peering_connection.installer_backplane_peering", "aws_vpc_peering_connection_accepter.peer"]
}

resource "aws_route" "company_public_route" {
  route_table_id            = "${module.company-vpc.public_route_table_ids[0]}"
  destination_cidr_block    = "${data.aws_subnet.installer_subnet.cidr_block}"
  vpc_peering_connection_id = "${aws_vpc_peering_connection.installer_backplane_peering.id}"
  depends_on                = ["module.company-vpc", "aws_vpc_peering_connection.installer_backplane_peering", "aws_vpc_peering_connection_accepter.peer"]
}

```

**Comment by smihajlovic-frame** [comment]
.tfvars file values:
```

company_vpc_cidr_block = "10.64.0.0/16"

company_vpc_public_subnet_cidr_blocks = ["10.64.4.0/24", "10.64.5.0/24"]

company_vpc_database_subnet_cidr_blocks = ["10.64.24.0/24", "10.64.25.0/24"]

company_vpc_private_subnet_cidr_blocks = ["10.64.44.0/24", "10.64.45.0/24"]

company_vpc_subnet_azs = ["us-east-1a", "us-east-1b"]

company_sitename = "demo"
```

**Comment by antonbabenko** [comment]
Looks good, but I have not had a chance to run this code myself (I will be offline the whole next week).

It can be that this module is not friendly-enough with VPC peering if you mix code and let Terraform/AWS to resolve dependencies automatically.

You can try to split the code into two steps - one create VPC and another create VPC peering and required routes.

Also, you can try to run `terraform apply -parallelism=1` to reduce the amount of potential eventual inconsistencies and hopefully find the problematic resources.

**Comment by smihajlovic-frame** [comment]
I have tried to run the code with `-parallelism=1` and still got some inconsistencies:

```
Error: Error applying plan:

2 error(s) occurred:

* aws_route.installer_route: 1 error(s) occurred:

* aws_route.installer_route: Error creating route: RouteAlreadyExists: The route identified by 10.64.0.0/16 already exists.
        status code: 400, request id: b14ed14a-ea59-406a-a7d3-f30de12c0b2c
* module.frame-vpc.aws_route.private_nat_gateway[1]: 1 error(s) occurred:

* aws_route.private_nat_gateway.1: Error creating route: RouteAlreadyExists: The route identified by 0.0.0.0/0 already exists.
        status code: 400, request id: 6e57e60b-6794-43d0-af71-b20e609f943d

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.



Error: Error applying plan:

1 error(s) occurred:

* aws_route.installer_route: 1 error(s) occurred:

* aws_route.installer_route: Error creating route: RouteAlreadyExists: The route identified by 10.64.0.0/16 already exists.
        status code: 400, request id: 073141e2-404c-4dba-a198-78943e930f82

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

```

**Comment by smihajlovic-frame** [comment]
I have tried specifying `-target=module.company-vpc` and omitting targets in next TF apply run (to create remaining resources), but got the same results.

**Comment by smihajlovic-frame** [comment]
I have tried to completely remove VPC peering and run Terraform. Still getting the same results, so the problem is not caused by VPC peering / VPC peering routes.

**Comment by antonbabenko** [comment]
I have just proof-read your code one more time and have few more comments/suggestions to check:
1. `data "aws_route_table" "installer_subnet_rt"` as well as all other data-sources are executed before the rest of the resources. Can it be that `aws_route.installer_route` resource has a route which is actually created before?
1. Try to manually delete that route using AWS console and see if it helps
1. Even better. Make it absolutely separated - VPC and VPC-peering. Run only the first one. Then Run only the second one. If it works separately - glue them together.
1. Error `aws_route.private_nat_gateway.1: Error creating route: RouteAlreadyExists: The route identified by 0.0.0.0/0 already exists.` seems not related to the rest of errors and probably should be fixed before. Split the code and make sure that `terraform-aws-modules/vpc/aws` module works with your settings and create the correct VPC.

Show the code as you split it, and try to fix fewer problems at once :)

**Comment by antonbabenko** [comment]
@smihajlovic-frame I am quite certain that this issue is now fixed in #111 and [v1.27.0](https://github.com/terraform-aws-modules/terraform-aws-vpc/releases/v1.27.0) has been released.

Please give it a try and leave a comment if the problem still exists.

**Comment by smihajlovic-frame** [comment]
@antonbabenko I have tested v1.27.0 and the behavior is still the same. I have completely removed everything that isn't part of the terraform-aws-vpc module, here is the code as tested:

```
module "company-vpc" {
  source  = "terraform-aws-modules/vpc/aws"
  version = "1.27.0"

  name = "Frame - ${var.company_sitename}"
  cidr = "${var.company_vpc_cidr_block}"

  azs              = "${var.company_vpc_subnet_azs}"
  private_subnets  = "${var.company_vpc_private_subnet_cidr_blocks}"
  public_subnets   = "${var.company_vpc_public_subnet_cidr_blocks}"
  database_subnets = "${var.company_vpc_database_subnet_cidr_blocks}"

  enable_nat_gateway               = true
  enable_dhcp_options              = true
  dhcp_options_domain_name         = "ec2.internal"
  dhcp_options_domain_name_servers = ["AmazonProvidedDNS"]

  create_database_subnet_group = false
  create_vpc                   = "${var.vpc_create}"
}
```

> Error: Error applying plan:
> 
> 3 error(s) occurred:
> 
> * module.company-vpc.aws_vpc_dhcp_options.this: 1 error(s) occurred:
> 
> * aws_vpc_dhcp_options.this: Error waiting for DHCP Options (dopt-1eaeae66) to become available: InvalidDhcpOptionID.NotFound: The dhcpOption ID 'dopt-1eaeae66' does not exist
>         status code: 400, request id: 80f1419d-4c6c-48ed-8651-8ede00aa18bb
> * module.company-vpc.aws_route.private_nat_gateway[1]: 1 error(s) occurred:
> 
> * aws_route.private_nat_gateway.1: Error finding route after creating it: Unable to find matching route for Route Table (rtb-a0385edc) and destination CIDR block (0.0.0.0/0).
> * module.company-vpc.aws_route.private_nat_gateway[0]: 1 error(s) occurred:
> 
> * aws_route.private_nat_gateway.0: Error finding route after creating it: Unable to find matching route for Route Table (rtb-ed355391) and destination CIDR block (0.0.0.0/0).
> 
> Terraform does not automatically rollback in the face of errors.
> Instead, your Terraform state file has been partially updated with
> any resources that successfully completed. Please address the error
> above and apply again to incrementally change your infrastructure.

The DHCP option set error happens in roughly 10% of runs also, but let's not tackle this in this issue.

Additional info:
I am authenticated using IAM role (instance metadata). Here is my aws provider config:
```
provider "aws" {
  version     = "~> 1.13"
  max_retries = 5
  region      = "${var.region}"
}
```

**Comment by antonbabenko** [comment]
If skip DHCP related errors then there are no `RouteAlreadyExists` errors in your output. `RouteAlreadyExists` is gone, right? :)

**Comment by smihajlovic-frame** [comment]
Yes, but errors from original issue post are still around ( `Unable to find matching route for Route Table` )

**Comment by antonbabenko** [comment]
RouteAlreadyExists is different and was fixed - this is an important information.

Now, the remaining problems could be fixed by tainting failed resources and recreating them (`terraform taint ...` and then `terraform apply`).

**Comment by smihajlovic-frame** [comment]
@antonbabenko I have successfully tested, and got consistent result with all `aws_route` resources. The trick is to set custom timeouts for `create` on all `aws_route` resources.

Here is what I changed (if you give me access I can create a PR):

```
resource "aws_route" "public_internet_gateway" {
  count = "${var.create_vpc && length(var.public_subnets) > 0 ? 1 : 0}"

  route_table_id         = "${aws_route_table.public.id}"
  destination_cidr_block = "0.0.0.0/0"
  gateway_id             = "${aws_internet_gateway.this.id}"

  timeouts {
    create = "5m"
  }

}

```

and:

```
resource "aws_route" "private_nat_gateway" {
  count = "${var.create_vpc && var.enable_nat_gateway ? length(var.private_subnets) : 0}"

  route_table_id         = "${element(aws_route_table.private.*.id, count.index)}"
  destination_cidr_block = "0.0.0.0/0"
  nat_gateway_id         = "${element(aws_nat_gateway.this.*.id, count.index)}"

  timeouts {
    create = "5m"
  }

}
```

**Comment by smihajlovic-frame** [comment]
I am creating and destroying the whole environment, not reapplying over some existing infrastructure. This is definitely affecting everyone, since I just want to create a VPC similar (even less complex) from the one in examples ( https://github.com/terraform-aws-modules/terraform-aws-vpc/blob/master/examples/complete-vpc/main.tf ).

The problem is that once NAT or IGW is provisioned, aws_route is created, and usually it takes AWS more than two minutes to create the route. Everyone who uses IGW/NAT is affected by this, but not everyone is having this module used to reprovision VPC ten times in a row.

**Comment by antonbabenko** [comment]
Yes, I agree with what you are saying. Could you please submit a PR with timeouts?
